---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless NodeJS Application/API powered by API Gateway and Lambda

Parameters:
  DbName:
    Type: String
    Default: public
  DbUser:
    Type: String
    Default: admin
  DbPassword:
    NoEcho: true
    Type: String
    Default: supercrazysecretpassword
  CookieSecret:
    NoEcho: true
    Type: String
    Default: serverlesssupersecretcookiesecret

Resources:

  #########################
  # DB
  #########################
  DbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: !Ref DbName
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: 5.7.mysql_aurora.2.09.2 # find more with aws rds describe-db-engine-versions --engine aurora-mysql --query "DBEngineVersions[].EngineVersion"
      EnableHttpEndpoint: true
      ScalingConfiguration:
        MaxCapacity: 4
        MinCapacity: 1
        AutoPause: true
        SecondsUntilAutoPause: 300
  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-DbSecret
      Description: This contains the RDS Master user credentials for RDS Aurora Serverless Cluster
      SecretString: 
        !Sub |
          {
            "username": "${DbUser}",
            "password": "${DbPassword}"
          }
  

  #########################
  # File Storage
  #########################
  S3Bucket:
    Type: AWS::S3::Bucket
    # DependsOn: BucketPermission
    # Properties:
      # BucketName: !Ref BucketName

  
  #########################
  # IAM Role
  #########################
  LambdaRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: [sts:AssumeRole]
      Path: "/"
      Policies:
        - PolicyName: LambdaToCloudWatchLogs
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action: logs:*
                Resource: [arn:aws:logs:*:*:*]
        - PolicyName: LambdaToRDSAuroraServerless
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action: rds-data:*
                Resource: 
                  - !Sub arn:aws:rds:*:*:cluster:${DbCluster}
                  - !Sub arn:aws:rds:*:*:cluster:${DbCluster}:*
        - PolicyName: LambdaToAWSSecrets
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource:
                  - !Ref DbSecret
                  - !Sub ${DbSecret}:*
        - PolicyName: LambdaToS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: !Sub arn:aws:s3:::${S3Bucket}/*

  
  
  #########################
  # Public API
  #########################
  ApiGateway:
    Type: AWS::Serverless::HttpApi
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambda.handler
      MemorySize: 256
      Runtime: nodejs14.x
      Timeout: 60 # Max=900; API Gateway times out at 28s, so no point in making much higher
      # Tracing: Active # TODO: Get this working
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
      Environment:
        Variables:
          NODE_ENV: production
          cookieSecret: !Ref CookieSecret
          dbName: !Ref DbName
          dbArn: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${DbCluster}
          dbSecretArn: !Ref DbSecret
          s3Bucket: !Ref S3Bucket
      Role: !GetAtt LambdaRole.Arn

      
Outputs:
  CloudFormation:
    Description: Console URL for the Stack.
    Value: https://console.aws.amazon.com/cloudformation/home

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/

  DbName:
    Description: Database Name
    Value: !Ref DbName
  
  DbArn:
    Description: Database ARN
    Value: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${DbCluster}

  DbName:
    Description: Database Secret ARN
    Value: !Ref DbSecret
  
  S3Bucket:
    Description: S3 Storage Bucket
    Value: !Ref S3Bucket
